;;; Automatically generated by ‘recentf’ on Wed Apr 22 21:13:30 2026.

(setq recentf-list
      '(
        "~/dotfiles/.emacs.d/lisp/plugins/project.el"
        "~/dotfiles/.emacs.d/init.el"
        "~/.emacs.d/init.el"
        "~/dotfiles/.emacs.d/lisp/plugins/welcome.el"
        "~/.emacs.d/lisp/plugins/dashboard.el~"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
