;;; Automatically generated by ‘recentf’ on Thu Apr 23 19:17:22 2026.

(setq recentf-list
      '(
        "~/dotfiles/.emacs.d/lisp/plugins/helpers.el"
        "~/.emacs.d/lisp/plugins/helpers.el"
        "~/.emacs.d/lisp/plugins/welcome.el"
        "~/dotfiles/.emacs.d/lisp/config/common.el"
        "~/.emacs.d/lisp/config/common.el"
        "~/.emacs.d/lisp/plugins/space.el"
        "~/dotfiles/.emacs.d/init.el"
        "~/.emacs.d/init.el"
        "~/dotfiles/.emacs.d/lisp/plugins/welcome.el"
        "~/.emacs.d/lisp/plugins/dashboard.el~"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
