;; -*- mode: emacs-lisp; coding: utf-8-unix -*-
;; Minibuffer history file, automatically generated by ‘savehist’.

(setq savehist-minibuffer-history-variables '(consult--buffer-history minibuffer-history-search-history consult--line-history buffer-name-history read-number-history magit-revision-history extended-command-history file-name-history))
(setq buffer-name-history '("completions.el" "main.c"))
(setq magit-revision-history '("master"))
(setq extended-command-history '("eglot" "apheleia-format-buffer" "list-packages" "dired" "magit-status" "list-packages"))
(setq file-name-history '("~/.emacs.d/lisp/plugins/helpers.el" "~/dotfiles/.emacs.d/init.el" "~/dotfiles/.emacs.d/lisp/plugins/project.el" "~/dotfiles/.emacs.d/lisp/plugins/helpers.el" "~/.emacs.d/lisp/plugins/completions.el" "~/dev/c-lang/main.c" "~/dotfiles/.emacs.d/lisp/plugins/completions.el" "~/dotfiles/.emacs.d/lisp/plugins/helpers.el" "~/.emacs.d/lisp/plugins/completions.el" "~/dev/c-lang/main.c" "~/.emacs.d/lisp/config/modeline.el" "~/dev/scale/react_scale/"))
(setq projectile-project-command-history '#s(hash-table test equal))
