[mgr]
ratio		=	[0,3,5]
sort_by		=	"alphabetical"
sort_sensitive	=	false
sort_dir_first	=	true
show_hidden	=	false
show_symlink	=	true

[preview]
tab_size	=	8
image_filter	=	"nearest"
image_quality	=	80
