(setq inhibit-startup-screen t)
(setq initial-scrathc-message nil)
(setq sentent-end-double-space nil)
(setq ring-bell-function 'ignore)
(setq-default indent-tabs-mode nil)
(setq-default tab-width 4)
(column-number-mode t)
(global-display-line-numbers-mode t)

(provide 'common)
